language: php
dist: trusty
sudo: false
php:
- 5.6
- 7.0
- 7.1
- hhvm
install:
  - travis_retry composer install --no-interaction
before_script:
  - mkdir -p build/logs
script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'